CREATE (Anakin:person {gender:"male"})
CREATE (C3PO:robot {color:["golden","silver"]})
CREATE (Luke:person {gender:"male"})
CREATE (Padmé:person {gender:"female"})
CREATE (R2D2:robot)
CREATE (Padmé)-[:owns {episode:1}]->(R2D2)
CREATE (Anakin)-[:owns {episode:2}]->(R2D2)
CREATE (Anakin)-[:child {episode:3}]->(Luke)
CREATE (Padmé)-[:child {episode:3}]->(Luke)
CREATE (Luke)-[:owns {episode:4}]->(R2D2)
CREATE (Luke)-[:owns {episode:4}]->(C3PO)
